POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "adaaa lovelace",
    "number": "11-111111113"
}

###
PUT http://localhost:3001/api/persons/632aed401901e11117aa8a39
content-type: application/json

{
    "name": "",
    "number": "050 142424"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "kalle",
    "number": ""
}